# Colors (Everforest Light Medium)

[colors.primary]
background = '#fdf6e3'
foreground = '#5c6a72'

[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'

[colors.bright]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#e0dcc7'

[colors.selection]
background = '#eaedc8'
text       = '#5c6a72'

[colors.search.matches]
background = '#8da101'
foreground = '#fdf6e3'

[colors.search.focused_match]
background = '#f85552'
foreground = '#fdf6e3'
