# Colors (Everforest Dark Soft)

[colors.primary]
background = '#333c43'
foreground = '#d3c6aa'

[colors.normal]
black   = '#4d5960'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.bright]
black   = '#4d5960'
red     = '#e67e80'
green   = '#a7c080'
yellow  = '#dbbc7f'
blue    = '#7fbbb3'
magenta = '#d699b6'
cyan    = '#83c092'
white   = '#d3c6aa'

[colors.selection]
background = '#5c3f4f'
text       = '#d3c6aa'

[colors.search.matches]
background = '#a7c080'
foreground = '#333c43'

[colors.search.focused_match]
background = '#e67e80'
foreground = '#333c43'
