# Colors (Everforest Light Soft)

[colors.primary]
background = '#f3ead3'
foreground = '#5c6a72'

[colors.normal]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#d8d3ba'

[colors.bright]
black   = '#5c6a72'
red     = '#f85552'
green   = '#8da101'
yellow  = '#dfa000'
blue    = '#3a94c5'
magenta = '#df69ba'
cyan    = '#35a77c'
white   = '#d8d3ba'

[colors.selection]
background = '#e1e4bd'
text       = '#5c6a72'

[colors.search.matches]
background = '#8da101'
foreground = '#f3ead3'

[colors.search.focused_match]
background = '#f85552'
foreground = '#f3ead3'
